from typing import Dict, Any, List, Optional, Tuple

def apply_action(game_state: Dict[str, Any], action: str) -> Dict[str, Any]: ...
def get_legal_actions(game_state: Dict[str, Any]) -> List[str]: ...
def mcts_search(
    game_state: Dict[str, Any],
    time_limit_sec: float = 1.0,
    num_simulations: int = 50,
    c_puct: float = 1.25,
    root_priors: Optional[Dict[str, float]] = None
) -> Tuple[str, List[Tuple[str, float]]]: ...
def initialize_registry(skills_dir: str) -> None: ...
def add_card(card_dict: Dict[str, Any]) -> None: ...
def score_action(game_state: Dict[str, Any], action: str) -> float: ...
def score_state(game_state: Dict[str, Any]) -> float: ...
