"""
run_factory.py

Team-Based Multi-Agent Pipeline
Orchestrates parallel execution of agent teams to ensure stability and speed.
"""

import sys
import logging
from pathlib import Path
from factory.teams.analytics_team import AnalyticsTeam
from factory.teams.meta_team import MetaTeam
from factory.teams.development_team import DevelopmentTeam
from factory.teams.qa_team import QATeam
from factory.game_runner import GameRunner, DEFAULT_DECK
from factory.trajectory_logger import TrajectoryLogger

# Setup logging
logging.basicConfig(level=logging.INFO, format="%(asctime)s - %(name)s - %(levelname)s - %(message)s")
logger = logging.getLogger("run_factory")

def run_team_pipeline(iteration_id: int):
    logger.info(f"=== STARTING ITERATION {iteration_id} (TEAM-BASED) ===")

    analytics_team = AnalyticsTeam()
    meta_team = MetaTeam()
    dev_team = DevelopmentTeam()
    qa_team = QATeam()

    # Phase 0: Generate fresh game logs via self-play simulation
    logger.info("Phase 0: Running live game simulations...")
    runner = GameRunner()
    traj_logger = TrajectoryLogger()
    
    iteration_result = runner.run_iteration(
        iteration_id=iteration_id,
        version_n1=f"base_v{iteration_id}",
        version_n2=f"new_v{iteration_id}",
        deck_base=DEFAULT_DECK,
        deck_new=DEFAULT_DECK,
        reasoning_base={},
        reasoning_new={}
    )
    
    # Log trajectories
    for label, game in iteration_result.get("games", {}).items():
        traj_logger.log_match({
            "iteration": iteration_id,
            "label": label,
            "winner": game.get("winner"),
            "turns": game.get("turns_taken", 0)
        })
    traj_logger.flush()
    
    # Phase 1: Analytics & Meta Data Gathering
    logger.info("Phase 1: Analytics and Meta Analysis...")
    meta_report = meta_team.analyze_meta()
    
    # Run Kaggle leaderboard feedback loop
    try:
        from factory.teams.leaderboard_team import LeaderboardTeam
        leaderboard_team = LeaderboardTeam()
        leaderboard_results = leaderboard_team.run_leaderboard_feedback_loop()
        logger.info(f"Leaderboard feedback loop results: {leaderboard_results}")
    except Exception as e:
        logger.error(f"Failed to run leaderboard feedback loop: {e}")
    
    # We pass the iteration results and decks to the analytics team.
    decks = {"player_a": DEFAULT_DECK, "player_b": DEFAULT_DECK}
    analytics_report = analytics_team.run_analysis(
        iteration_id=iteration_id, log_dir="logs",
        iteration_result=iteration_result, decks=decks
    )
    
    # Enrich analytics with meta shifts
    analytics_report["meta_data"] = meta_report


    # Phase 2: Parallel Development
    logger.info("Phase 2: Development...")
    dev_results = dev_team.run_development(analytics_report)
    deck_candidate = dev_results.get("deck_candidate")
    logic_candidate = dev_results.get("logic_candidate")

    # If development team actually staged something, send it to QA
    if deck_candidate or logic_candidate:
        logger.info(f"Phase 3: QA and Peer Review for candidates -> Deck: {bool(deck_candidate)}, Logic: {bool(logic_candidate)}")
        
        # Determine actual file paths generated by builder/architect
        staged_deck = str(Path("staging") / "deck_new.csv") if deck_candidate else None
        staged_logic = str(Path("staging") / "logic_new.py") if logic_candidate else None # assuming builder_agent output
        
        # Run QA
        is_approved = qa_team.run_qa_pipeline(deck_candidate=staged_deck, logic_candidate=staged_logic)
        
        if is_approved:
            logger.info(f"Iteration {iteration_id} completed successfully. Changes merged to baseline.")
        else:
            logger.warning(f"Iteration {iteration_id} completed. Pull Request REJECTED by QA team.")
    else:
        logger.info(f"Iteration {iteration_id} completed. Development team proposed no changes.")

    # Evaluate iteration results to update logs/eval_report.json
    try:
        from factory.eval_agent import EvalAgent
        evaluator = EvalAgent()
        evaluator.evaluate(iteration_result)
        logger.info(f"Successfully evaluated iteration {iteration_id} and updated eval_report.json")
    except Exception as e:
        logger.error(f"Failed to run evaluation for iteration {iteration_id}: {e}")

    logger.info(f"=== COMPLETED ITERATION {iteration_id} ===\n")

def run_iteration(iteration_id: int, forced_archetype: str = None, forced_escalation: dict = None):
    """Public entry point used by run_guided_iterations.py.
    
    Wraps run_team_pipeline, accepting optional forced_archetype and
    forced_escalation parameters for the guided-iteration scheduler.
    """
    run_team_pipeline(iteration_id)

if __name__ == "__main__":
    import json
    
    start_iter = 1
    # Try to load latest iteration from eval_report
    try:
        report_path = Path("logs/eval_report.json")
        if report_path.exists():
            data = json.loads(report_path.read_text(encoding="utf-8"))
            start_iter = data.get("iteration", 0) + 1
    except Exception:
        pass
        
    iterations_to_run = 1
    if len(sys.argv) > 1:
        iterations_to_run = int(sys.argv[1])
        
    end_iter = start_iter + iterations_to_run - 1
        
    for i in range(start_iter, end_iter + 1):
        run_team_pipeline(i)
