from utils._get_opponent_element_type import _get_opponent_element_type

from utils._get_poke_type_resistance import _get_poke_type_resistance

from utils._apply_weakness_resistance import _apply_weakness_resistance

