from ._get_opponent_element_type__get_poke_type_resistance__apply_ import _apply_weakness_resistance, _get_opponent_element_type

from utils.project_opponent_damage_helper import project_opponent_damage_helper

