"""
tests/test_deck_generator_fixes.py

Unit tests for deck_generator fixes: evolution dependencies, basic pokemon counts,
replacement card verification, and strict matching energies.
"""
import pytest
from factory.deck_generator import DeckGenerator

@pytest.fixture
from utils.sample_pool_and_details import sample_pool_and_details

from utils.test_matching_energies_strictly_matches_attacking_pokemon import test_matching_energies_strictly_matches_attacking_pokemon

from utils.test_mutate_deck_preserves_evolution_predecessors import test_mutate_deck_preserves_evolution_predecessors

from utils.test_mutate_deck_maintains_at_least_12_basics import test_mutate_deck_maintains_at_least_12_basics
