"""Shared dimensions for aligned state tensors."""

MAX_HAND = 20
MAX_BOARD = 20
MAX_PRIZES = 6
MAX_OPP_VISIBLE = 20
META_FEATURES = 5

SINGLE_STATE_DIM = MAX_HAND + MAX_BOARD + MAX_PRIZES + MAX_OPP_VISIBLE + META_FEATURES
STACK_SIZE = 3
STATE_DIM = SINGLE_STATE_DIM * STACK_SIZE
