
def _ensure_quoted_url(url: str) -> str:
    """
    Make sure a link is fully quoted.
    For example, if ' ' occurs in the URL, it will be replaced with "%20",
    and without double-quoting other characters.
    """
    # Split the URL into parts according to the general structure
    # `scheme://netloc/path?query#fragment`.
    result = urllib.parse.urlsplit(url)
    # If the netloc is empty, then the URL refers to a local filesystem path.
    is_local_path = not result.netloc
    path = _clean_url_path(result.path, is_local_path=is_local_path)
    # Temporarily replace scheme with file to ensure the URL generated by
    # urlunsplit() contains an empty netloc (file://) as per RFC 1738.
    ret = urllib.parse.urlunsplit(result._replace(scheme="file", path=path))
    ret = result.scheme + ret[4:]  # Restore original scheme.
    return ret

