
def epps_singleton_2samp(x, y, t=(0.4, 0.8), *, axis=0):
    """Compute the Epps-Singleton (ES) test statistic.

    Test the null hypothesis that two samples have the same underlying
    probability distribution.

    Parameters
    ----------
    x, y : array-like
        The two samples of observations to be tested. Input must not have more
        than one dimension. Samples can have different lengths, but both
        must have at least five observations.
    t : array-like, optional
        The points (t1, ..., tn) where the empirical characteristic function is
        to be evaluated. It should be positive distinct numbers. The default
        value (0.4, 0.8) is proposed in [1]_. Input must not have more than
        one dimension.
    axis : int or tuple of ints, default: 0
        If an int or tuple of ints, the axis or axes of the input along which
        to compute the statistic. The statistic of each axis-slice (e.g. row)
        of the input will appear in a corresponding element of the output.
        If ``None``, the input will be raveled before computing the statistic.

    Returns
    -------
    statistic : float
        The test statistic.
    pvalue : float
        The associated p-value based on the asymptotic chi2-distribution.

    See Also
    --------
    ks_2samp, anderson_ksamp

    Notes
    -----
    Testing whether two samples are generated by the same underlying
    distribution is a classical question in statistics. A widely used test is
    the Kolmogorov-Smirnov (KS) test which relies on the empirical
    distribution function. Epps and Singleton introduce a test based on the
    empirical characteristic function in [1]_.

    One advantage of the ES test compared to the KS test is that is does
    not assume a continuous distribution. In [1]_, the authors conclude
    that the test also has a higher power than the KS test in many
    examples. They recommend the use of the ES test for discrete samples as
    well as continuous samples with at least 25 observations each, whereas
    `anderson_ksamp` is recommended for smaller sample sizes in the
    continuous case.

    The p-value is computed from the asymptotic distribution of the test
    statistic which follows a `chi2` distribution. If the sample size of both
    `x` and `y` is below 25, the small sample correction proposed in [1]_ is
    applied to the test statistic.

    The default values of `t` are determined in [1]_ by considering
    various distributions and finding good values that lead to a high power
    of the test in general. Table III in [1]_ gives the optimal values for
    the distributions tested in that study. The values of `t` are scaled by
    the semi-interquartile range in the implementation, see [1]_.

    References
    ----------
    .. [1] T. W. Epps and K. J. Singleton, "An omnibus test for the two-sample
       problem using the empirical characteristic function", Journal of
       Statistical Computation and Simulation 26, p. 177--203, 1986.

    .. [2] S. J. Goerg and J. Kaiser, "Nonparametric testing of distributions
       - the Epps-Singleton two-sample test using the empirical characteristic
       function", The Stata Journal 9(3), p. 454--465, 2009.

    Examples
    --------
    Generate random samples ``x`` and ``y``.

    >>> import numpy as np
    >>> from scipy import stats
    >>> rng = np.random.default_rng(66326777)
    >>> x = rng.normal(0, 1, size=100)
    >>> y = rng.normal(5, 3, size=100)

    Test the null hypothesis that ``x`` and ``y`` are sampled from the same
    distribution.

    >>> res = stats.epps_singleton_2samp(x, y)
    >>> res.statistic
    np.float64(316.6441136688085)
    >>> res.pvalue
    np.float64(2.778946959815902e-67)
    
    The large value of the statistic and small p-value may be taken as evidence that
    ``x`` and ``y`` were not sampled from the same distribution. 
    """
    xp = array_namespace(x, y)
    # x and y are converted to arrays by the decorator
    # and `axis` is guaranteed to be -1.
    x, y = xp_promote(x, y, force_floating=True, xp=xp)
    t = xp.asarray(t, dtype=x.dtype)
    # check if x and y are valid inputs
    nx, ny = x.shape[-1], y.shape[-1]
    if (nx < 5) or (ny < 5):  # only used by test_axis_nan_policy
        raise ValueError('x and y should have at least 5 elements, but len(x) '
                         f'= {nx} and len(y) = {ny}.')
    n = nx + ny

    # check if t is valid
    if t.ndim > 1:
        raise ValueError(f't must be 1d, but t.ndim equals {t.ndim}.')
    if is_lazy_array(t):
        t = xpx.at(t)[t <= 0].set(xp.nan)
    elif xp.any(t <= 0):
        raise ValueError('t must contain positive elements only.')

    # Previously, non-finite input caused an error in linalg functions.
    # To prevent an issue in one slice from halting the calculation, replace non-finite
    # values with a harmless one, and replace results with NaN at the end.
    i_x = ~xp.isfinite(x)
    i_y = ~xp.isfinite(y)
    # Ideally we would avoid copying all data here; see
    # discussion in data-apis/array-api-extra#506.
    x = xp.where(i_x, 1., x)
    y = xp.where(i_y, 1., y)
    invalid_result = xp.any(i_x, axis=-1) | xp.any(i_y, axis=-1)

    # rescale t with semi-iqr as proposed in [1]; import iqr here to avoid
    # circular import
    from scipy.stats import iqr
    sigma = iqr(xp.concat((x, y), axis=-1), axis=-1, keepdims=True) / 2
    ts = xp.reshape(t, (-1,) + (1,)*x.ndim) / sigma

    # covariance estimation of ES test
    gx = xp.concat((xp.cos(ts*x), xp.sin(ts*x)), axis=0)
    gy = xp.concat((xp.cos(ts*y), xp.sin(ts*y)), axis=0)
    gx, gy = xp.moveaxis(gx, 0, -2), xp.moveaxis(gy, 0, -2)
    cov_x = xpx.cov(gx) * (nx-1)/nx  # the test uses biased cov-estimate
    cov_y = xpx.cov(gy) * (ny-1)/ny
    cov_x, cov_y = xp.astype(cov_x, x.dtype), xp.astype(cov_y, y.dtype)
    est_cov = (n/nx)*cov_x + (n/ny)*cov_y
    est_cov_inv = xp.linalg.pinv(est_cov)
    r = xp.asarray(xp.linalg.matrix_rank(est_cov_inv), dtype=est_cov_inv.dtype)
    if not is_lazy_array(r) and xp.any(r < 2*xp_size(t)):
        warnings.warn('Estimated covariance matrix does not have full rank. '
                      'This indicates a bad choice of the input t and the '
                      'test might not be consistent.', # see p. 183 in [1]_
                      stacklevel=2)

    # compute test statistic w distributed asympt. as chisquare with df=r
    g_diff = xp.mean(gx, axis=-1, keepdims=True) - xp.mean(gy, axis=-1, keepdims=True)
    w = n*xp.matmul(xp.matrix_transpose(g_diff), xp.matmul(est_cov_inv, g_diff))
    w = w[..., 0, 0]

    # apply small-sample correction
    if (max(nx, ny) < 25):
        corr = 1.0/(1.0 + n**(-0.45) + 10.1*(nx**(-1.7) + ny**(-1.7)))
        w *= corr

    chi2 = _stats_py._SimpleChi2(r)
    p = _stats_py._get_pvalue(w, chi2, alternative='greater', symmetric=False, xp=xp)

    w = xpx.at(w)[invalid_result].set(xp.nan)
    p = xpx.at(p)[invalid_result].set(xp.nan)
    w = w[()] if w.ndim == 0 else w
    p = p[()] if p.ndim == 0 else p
    return Epps_Singleton_2sampResult(w, p)

