
def get_nn_functional_tests():
    nn_functional_tests = [
        ('conv1d', (S, S, S), ((S, S, S),)),
        ('conv2d', (S, S, S, S), ((S, S, S, S),)),
        ('conv3d', (S, S, S, S, S), ((S, S, S, S, S),)),
        ('conv_transpose1d', (S, S, S), ((S, S, S),)),
        ('conv_transpose2d', (S, S, S, S), ((S, S, S, S),)),
        ('conv_transpose3d', (S, S, S, S, S), ((S, S, S, S, S),)),
        ('conv_tbc', (S, S, S), ((S, S, S), (S,), 2)),
        ('avg_pool1d', (S, S, S), (3,)),
        ('avg_pool2d', (S, S, S, S), (3,), '', (True,)),
        ('avg_pool3d', (S, S, S, S, S), (3,)),
        ('fractional_max_pool2d', (S, S, S, S), (3, [2, 3],)),
        ('max_pool1d', (S, S, S), (2, 1)),
        ('max_pool1d', (S, S, S), (2, 1, 1, 1, False, True), 'with_indices'),
        ('max_pool2d', (S, S, S, S), (2, 1), '', (True, 'aten::max_pool2d_with_indices')),
        ('max_pool2d', (S, S, S, S), (2, 1, 1, 1, False, True), 'with_indices', (True, 'aten::max_pool2d_with_indices')),
        ('max_pool3d', (S, S, S, S, S), (2, 1)),
        ('max_unpool1d', torch.tensor([[[2., 4]]]), (torch.tensor([[[1, 3]]]), 2, 2, 0)),
        ('max_unpool2d', torch.tensor([[[[2., 4]]]]), (torch.tensor([[[[1, 3]]]]), 2, 2, 0)),
        ('max_unpool3d', torch.tensor([[[[[2., 4]]]]]), (torch.tensor([[[[[1, 3]]]]]), 2, 2, 0)),
        ('lp_pool1d', (S, S, S), (2., 3, 2,)),
        ('lp_pool2d', (S, S, S, S), (2., 3, 2,)),
        ('lp_pool3d', (S, S, S, S, S), (2., 3, 2,)),
        ('adaptive_max_pool1d', (S, S, S), (5,)),
        ('adaptive_max_pool2d', (S, S, S, S), ([5, 7],)),
        ('adaptive_max_pool3d', (S, S, S, S, S), ([3, 2, 2],)),
        ('adaptive_avg_pool1d', (S, S, S), (5,), '', (True,)),
        ('adaptive_avg_pool2d', (S, S, S, S), ([5, 7],), '', (True,)),
        ('adaptive_avg_pool3d', (S, S, S, S, S), ([3, 2, 2],), '', (True,)),
        ('dropout', (S, S, S), (0.5,), '', (True, 'aten::native_dropout')),
        ('alpha_dropout', (S, S, S), (0.5,)),
        ('dropout2d', (S, S, S), (0.5,)),
        ('dropout2d', (S, S, S, S), (0.5,), 'batched'),
        ('dropout3d', (S, S, S, S), (0.5,)),
        ('dropout3d', (S, S, S, S, S), (0.5,), 'batched'),
        ('feature_alpha_dropout', (S, S, S), (0.5,)),
        ('threshold', (S, S, S), (0.1, 2.), '', (True,)),
        ('threshold', (S, S, S), (0.1, 2., True), 'inplace'),
        ('relu', (S, S, S), (), '', (True,)),
        ('relu', (S, S, S), (), 'inplace'),
        ('glu', (S - 1, S - 1, S - 1), (),),
        ('hardtanh', (S, S, S), (-0.5, 0.5), '', (True,)),
        ('hardtanh', (S, S, S), (-0.5, 0.5, True), 'inplace'),
        ('relu6', (S, S, S), (), '', (True,)),
        ('relu6', (S, S, S), (True), 'inplace'),
        ('elu', (S, S, S), (0.9,),),
        ('elu', (S, S, S), (0.9, True), 'inplace'),
        ('selu', (S, S, S), (),),
        ('selu', (S, S, S), (True), 'inplace'),
        ('celu', (S, S, S), (0.9,),),
        ('celu', (S, S, S), (0.9, True), 'inplace'),
        ('leaky_relu', (S, S, S), (0.02,), '', (True,)),
        ('leaky_relu', (S, S, S), (0.02,), 'inplace'),
        ('rrelu', (S, S), (0.1, 0.3, False),),
        ('rrelu', (S, S), (0.1, 0.3, False, True), 'inplace'),
        ('hardshrink', (S, S, S), (0.4,), '', (True,)),
        ('tanhshrink', (S, S, S), (),),
        ('softsign', (S, S, S), (),),
        ('softplus', (S, S, S), (), '', (True,)),
        ('softmin', (S, S, S), (0,),),
        ('softmax', (S, S, S), (0,), '', (True,)),
        ('softmax', (S, S, S), (0, 3, torch.double), 'with_all_args', (True,)),
        ('tanh', (S, S, S), (), '', (True,)),
        ('sigmoid', (S, S, S), (), '', (True,)),
        ('silu', (S, S, S), (), '', (True,)),
        ('log_softmax', (S, S, S), (0,), '', (True,)),
        ('linear', (S, S), ((M, S),), '', (True, ['aten::linear'])),
        ('linear', (S, S), ((M, S), (M,)), 'addmm', (True, ['aten::linear'])),
        ('bilinear', (S, S, S), ((S, S, M), torch.zeros(M, S, M),),),
        ('embedding', torch.tensor([[1, 2, 4, 5], [4, 3, 2, 5]]), (torch.rand(6, 3), ), '', (True,)),
        ('embedding_bag', torch.tensor([1, 2, 4, 2]), (torch.rand(5, 3), torch.tensor([0, 4]),),),
        ('batch_norm', (S, S),
            (non_differentiable(torch.randn(S)), non_differentiable(torch.ones(S)), None, None, True, ),
            'training', (True, 'aten::_batch_norm_impl_index')),
        ('batch_norm', (0, S, S, S),
            (non_differentiable(torch.randn(S)), non_differentiable(torch.ones(S)),
             non_differentiable(torch.randn(S)), non_differentiable(torch.ones(S)), True, ),
            'size_zero', (True, 'aten::_batch_norm_impl_index')),
        ('batch_norm', (0, S, S, S),
            (non_differentiable(torch.randn(S)), non_differentiable(torch.ones(S)),
             non_differentiable(torch.randn(S)), non_differentiable(torch.ones(S)), True, ),
            'size_zero_inference', (True, 'aten::_batch_norm_impl_index')),
        ('batch_norm', (S, S),
            (non_differentiable(torch.randn(S)), non_differentiable(torch.ones(S)),
             non_differentiable(torch.randn(S)), non_differentiable(torch.ones(S)), True, ),
            'with_weight_and_bias_training', (True, 'aten::_batch_norm_impl_index')),
        ('batch_norm', (S, S), (non_differentiable(torch.randn(S)), non_differentiable(torch.ones(S)),
                                None, non_differentiable(torch.ones(S)), True, ),
            'with_only_bias_training', (True, 'aten::_batch_norm_impl_index')),
        ('batch_norm', (S, S), (non_differentiable(torch.randn(S)), non_differentiable(torch.ones(S)),
                                non_differentiable(torch.randn(S)), None, True, ),
            'with_only_weight_training', (True, 'aten::_batch_norm_impl_index')),
        ('batch_norm', (S, S), (non_differentiable(torch.randn(S)), non_differentiable(torch.ones(S)),
                                None, None, False, ),
            'inference', (True, 'aten::_batch_norm_impl_index')),
        ('batch_norm', (S, S), (non_differentiable(torch.randn(S)), non_differentiable(torch.ones(S)),
                                non_differentiable(torch.randn(S)), non_differentiable(torch.ones(S)), False, ),
            'with_weight_and_bias_inference', (True, 'aten::_batch_norm_impl_index')),
        ('batch_norm', (S, S), (non_differentiable(torch.randn(S)), non_differentiable(torch.ones(S)),
                                None, non_differentiable(torch.ones(S)), False, ),
            'with_only_bias_inference', (True, 'aten::_batch_norm_impl_index')),
        ('batch_norm', (S, S), (non_differentiable(torch.randn(S)), non_differentiable(torch.ones(S)),
                                non_differentiable(torch.randn(S)), None, False, ),
            'with_only_weight_inference', (True, 'aten::_batch_norm_impl_index')),
        ('instance_norm', (S, S, S), (non_differentiable(torch.zeros(S)), non_differentiable(torch.ones(S))),),
        ('layer_norm', (S, S, S, S), ([5],), '',
         (False, ['aten::contiguous', 'aten::_batch_norm_impl_index'])),
        ('layer_norm', (S, S, S, S), ([5], non_differentiable(torch.rand(S)),), 'with_only_weight',
         (False, ['aten::contiguous', 'aten::_batch_norm_impl_index'])),
        ('layer_norm', (S, S, S, S), ([5], None, non_differentiable(torch.rand(S)),), 'with_only_bias',
         (False, ['aten::contiguous', 'aten::_batch_norm_impl_index'])),
        ('layer_norm', (S, S, S, S), ([5], non_differentiable(torch.rand(S)),
                                      non_differentiable(torch.rand(S))), 'with_weight_and_bias',
         (False, ['aten::contiguous', 'aten::_batch_norm_impl_index', 'aten::addcmul'])),
        ('group_norm', (S, S, S), (1, torch.rand(5),),),
        ('local_response_norm', (S, S, S), (2, ),),
        ('nll_loss', F.log_softmax(torch.randn(3, 5), dim=0), (torch.tensor([1, 0, 4]),), '',),
        ('poisson_nll_loss', torch.rand(S, 2), (torch.rand(S, 2),),),
        ('poisson_nll_loss', torch.rand(S, 2), (torch.rand(S, 2), True, True), 'full'),
        ('kl_div', F.log_softmax(torch.randn(S, 10), 1), (F.softmax(torch.randn(S, 10), 1),),),
        ('cross_entropy', (3, S), (torch.randint(S, (3,), dtype=torch.int64),),),
        ('binary_cross_entropy_with_logits', (3,), (torch.empty(3).random_(2), ),),
        ('smooth_l1_loss', (3, S), (non_differentiable(torch.rand(3, S)),),),
        ('huber_loss', (3, S), (non_differentiable(torch.rand(3, S)),),),
        ('l1_loss', (3, S), (non_differentiable(torch.rand(3, S)),),),
        ('mse_loss', (3, S), (non_differentiable(torch.rand(3, S)),),),
        ('smooth_l1_loss', (3, S), ((torch.rand(3, S)),), 'with_grad'),
        ('huber_loss', (3, S), ((torch.rand(3, S)),), 'with_grad'),
        ('l1_loss', (3, S), ((torch.rand(3, S)),), 'with_grad'),
        ('mse_loss', (3, S), ((torch.rand(3, S)),), 'with_grad'),
        ('margin_ranking_loss', (S,), ((S,), (S,)),),
        ('hinge_embedding_loss', (3, S), (non_differentiable(torch.rand(3, S)),),),
        ('soft_margin_loss', (3, S), (non_differentiable(torch.rand(3, S)),),),
        ('multilabel_soft_margin_loss', (3, S), (non_differentiable(torch.rand(3, S)),),),
        ('cosine_embedding_loss', (S, S), ((S, S), non_differentiable(torch.rand(S,))),),
        ('pixel_shuffle', (1, 9, 4, 4), (3,),),
        ('pixel_unshuffle', (1, 1, 12, 12), (3,),),
        ('affine_grid', (S, 2, 3), (torch.Size([S, 1, 7, 7]),),),
        ('pad', (3, 3, 4, 2), ([1, 1],),),
        ('pairwise_distance', (S, S), ((S, S),),),
        ('pdist', (S, S), (),),
        ('cosine_similarity', (S, S), ((S, S),),),
        ('triplet_margin_loss', (S, S), ((S, S), (S, S)),),
        ('normalize', (S, S, S), (),),
        ('unfold', (S, S, S, S), ([2, 3]),),
        ('fold', (1, 3 * 2 * 2, 12), ([4, 5], [2, 2]),),
        ('grid_sample', (S, S, S, S), (non_differentiable(torch.rand(S, S, S, 2)),),),
        ('gumbel_softmax', (S, S), (2.,), '', (True, ['aten::softmax', 'aten::add', 'aten::div'], ['aten::neg'])),
        ('gumbel_softmax', (S, S), (2., True,), 'hard', (True, ['aten::softmax', 'aten::add', 'aten::div'], ['aten::neg'])),
        ('multilabel_margin_loss', torch.tensor([[0.2, -0.2, 0.07]]), (torch.tensor([[0, 0, 1]]),),),
        ('multi_margin_loss', (S, S), (non_differentiable(torch.randint(S, (S, ), dtype=torch.int64)),
                                       1, 1., non_differentiable(torch.randn(S))),),
        ('binary_cross_entropy', torch.randn(3, 2).sigmoid(), (non_differentiable(torch.rand(3, 2)),
                                                               non_differentiable(torch.randn(3, 2))),),
        ('binary_cross_entropy', torch.randn(3, 2).sigmoid(),
            (non_differentiable(torch.rand(3, 2)),
             non_differentiable(torch.randn(3, 2)), None, None, 'mean'), 'size_average'),
        ('ctc_loss', torch.rand(S, S, S).log_softmax(2).detach().requires_grad_(),
         (torch.randint(1, S, (S, S), dtype=torch.long), torch.full((S,), S, dtype=torch.long),
          torch.randint(1, S, (S,), dtype=torch.long))),
        ('upsample', torch.randn(S, S, M, M), (None, 2.), 'with_scale'),
        ('upsample', torch.randn(S, S, M, M), (4,), 'with_size'),
        ('interpolate', torch.zeros(3, 3).view(1, 1, 3, 3), (2,), 'nearest_4d'),
        ('interpolate', torch.randn(S, S, M, M), (None, 2.), 'nearest_4d_with_scale'),
        ('interpolate', torch.randn(S, S, M, M), (4,), 'nearest_4d_with_size'),
        ('interpolate', torch.zeros(3, 3).view(1, 1, 3, 3), (2,), 'area_4d'),
        ('interpolate', torch.randn(S, S, M, M), (None, 2.), 'area_4d_with_scale'),
        ('interpolate', torch.randn(S, S, M, M), (4,), 'area_4d_with_size'),
        ('interpolate', torch.zeros(3, 3).view(1, 1, 3, 3), (2,), 'bilinear_4d'),
        ('interpolate', torch.randn(S, S, M, M), (None, 2.), 'bilinear_4d_with_scale'),
        ('interpolate', torch.randn(S, S, M, M), (4,), 'bilinear_4d_with_size'),
        ('interpolate', torch.zeros(3, 3).view(1, 1, 3, 3), (2,), 'bicubic_4d'),
        ('interpolate', torch.randn(S, S, M, M), (None, 2.), 'bicubic_4d_with_scale'),
        ('interpolate', torch.randn(S, S, M, M), (4,), 'bicubic_4d_with_size'),
        ('interpolate', torch.zeros(3, 3).view(1, 3, 3), (2,), 'nearest_3d'),
        ('interpolate', torch.randn(S, M, M), (None, 2.), 'nearest_3d_with_scale'),
        ('interpolate', torch.randn(S, M, M), (4,), 'nearest_3d_with_size'),
        ('interpolate', torch.zeros(3, 3).view(1, 3, 3), (2,), 'area_3d'),
        ('interpolate', torch.randn(S, M, M), (None, 2.), 'area_3d_with_scale'),
        ('interpolate', torch.randn(S, M, M), (4,), 'area_3d_with_size'),
        ('interpolate', torch.zeros(3, 3).view(1, 3, 3), (2,), 'linear_3d'),
        ('interpolate', torch.randn(S, M, M), (None, 2.), 'linear_3d_with_scale'),
        ('interpolate', torch.randn(S, M, M), (4,), 'linear_3d_with_size'),
        ('interpolate', torch.randn(S, M, M, M, M), (None, 2.), 'nearest_5d_with_scale'),
        ('interpolate', torch.randn(S, M, M, M, M), (4,), 'nearest_5d_with_size'),
        ('interpolate', torch.zeros(3, 3, 3).view(1, 1, 3, 3, 3), (2,), 'area_5d'),
        ('interpolate', torch.randn(S, M, M, M, M), (None, 2.), 'area_5d_with_scale'),
        ('interpolate', torch.randn(S, M, M, M, M), (4,), 'area_5d_with_size'),
        ('interpolate', torch.zeros(3, 3, 3).view(1, 1, 3, 3, 3), (2,), 'trilinear_5d'),
        ('interpolate', torch.randn(S, M, M, M, M), (None, 2.), 'trilinear_5d_with_scale'),
        ('interpolate', torch.randn(S, M, M, M, M), (4,), 'trilinear_5d_with_size'),
        ('interpolate', torch.zeros(3, 3).view(1, 1, 3, 3), (2, None, 'nearest', None, False),
         'nearest_4d_not_recompute_scale_factor'),
        ('interpolate', torch.randn(S, S, M, M), (4, None, 'nearest', None, False),
         'nearest_4d_with_size_not_recompute_scale_factor'),
        ('interpolate', torch.randn(S, S, M, M), (None, 2., 'bilinear', None, False),
         'bilinear_4d_with_scale_not_recompute_scale_factor'),
        ('interpolate', torch.randn(S, S, M, M), (4, None, 'bilinear', None, False),
         'bilinear_4d_with_size_not_recompute_scale_factor'),
        ('interpolate', torch.randn(S, S, M, M), (None, 2., 'bicubic', None, False),
         'bicubic_4d_with_scale_not_recompute_scale_factor'),
        ('interpolate', torch.randn(S, S, M, M), (4, None, 'bicubic', None, False),
         'bicubic_4d_with_size_not_recompute_scale_factor'),
        ('interpolate', torch.randn(S, M, M), (None, 2., 'nearest', None, False),
         'nearest_3d_with_scale_not_recompute_scale_factor'),
        ('interpolate', torch.randn(S, M, M), (4, None, 'nearest', None, False),
         'nearest_3d_with_size_not_recompute_scale_factor'),
        ('interpolate', torch.randn(S, M, M), (None, 2., 'linear', None, False),
         'linear_3d_with_scale_not_recompute_scale_factor'),
        ('interpolate', torch.randn(S, M, M), (4, None, 'linear', None, False),
         'linear_3d_with_size_not_recompute_scale_factor'),
        ('interpolate', torch.randn(S, M, M, M, M), (None, 2., 'nearest', None, False),
         'nearest_5d_with_scale_not_recompute_scale_factor'),
        ('interpolate', torch.randn(S, M, M, M, M), (4, None, 'nearest', None, False),
         'nearest_5d_with_size_not_recompute_scale_factor'),
        ('interpolate', torch.randn(S, M, M, M, M), (None, 2., 'trilinear', None, False),
         'trilinear_5d_with_scale_not_recompute_scale_factor'),
        ('interpolate', torch.randn(S, M, M, M, M), (4, None, 'trilinear', None, False),
         'trilinear_5d_with_size_not_recompute_scale_factor'),
    ]
    return nn_functional_tests

