from typing import List

def get_network_output_batched(
    net_apply: ApplyFn, net_params: Params, net_input: np.ndarray,
    all_illegal_actions: List[List[int]],
    key: hk.PRNGSequence) -> List[jax.Array]:
  """Returns policy of batched input generated as output of model.

  Args:
    net_apply: Haiku apply function.
    net_params: Haiku network parameters.
    net_input: Input of the model.
    all_illegal_actions: Nested list of illegal actions we use to mask the model
      output. Length of outer list is equal to the batch size.
    key: Pseudo random number.

  Returns:
    List of policies generated by model. Model output is filtered to mask
    illegal actions. Length of the returned list is equal to batch size.
  """
  net_output_batched = net_apply(net_params, next(key), net_input)

  batch_policies = []
  for i, illegal_actions in enumerate(all_illegal_actions):
    net_output = net_output_batched[i]
    if illegal_actions:
      net_output = jnp.expand_dims(
          jnp.delete(net_output, jnp.array(illegal_actions)), axis=0)

    batch_policies.append(jax.nn.softmax(net_output))
  return batch_policies

