
def get_network_output(net_apply: ApplyFn, net_params: Params,
                       net_input: np.ndarray, illegal_actions: List[int],
                       key: hk.PRNGSequence) -> jax.Array:
  """Returns policy generated as output of model.

  Args:
    net_apply: Haiku apply function.
    net_params: Haiku network parameters.
    net_input: Input of the model.
    illegal_actions: List of illegal actions we use to mask the model output.
    key: Pseudo random number.

  Returns:
    Policy generated by model. Model output is filtered to mask illegal actions.
  """
  net_output = jax.jit(net_apply)(net_params, key, net_input)

  if illegal_actions:
    net_output = jnp.delete(net_output, np.array(illegal_actions))

  return jax.nn.softmax(net_output)

