
def local_definitions(
    names: SymbolTable, name_prefix: str, info: TypeInfo | None = None, impl_only: bool = False
) -> Iterator[Definition]:
    """Iterate over local definitions (not imported) in a symbol table.

    Recursively iterate over class members and nested classes. If impl_only is True, do
    not yield the classes themselves, only methods.
    """
    # TODO: What should the name be? Or maybe remove it?
    for name, symnode in names.items():
        shortname = name
        if "-redef" in name:
            # Restore original name from mangled name of multiply defined function
            shortname = name.split("-redef")[0]
        fullname = name_prefix + "." + shortname
        node = symnode.node
        if node and node.fullname == fullname:
            yield_node = True
            if impl_only:
                if not isinstance(node, (FuncDef, OverloadedFuncDef, Decorator)):
                    yield_node = False
                else:
                    impl = node.func if isinstance(node, Decorator) else node
                    yield_node = not impl.def_or_infer_vars
                    # This logic for plugin generated nodes preserves historical behavior.
                    # On one hand, we generally type-check plugin generated nodes, since
                    # some 3rd party plugins may rely on this behavior. On the other hand
                    # we skip nodes generated by mypy itself, these nodes are not added to
                    # the class AST (only to symbol table) as they often cut corners.
                    if symnode.plugin_generated and info and node not in info.defn.defs.body:
                        yield_node = False
            if isinstance(node, (FuncDef, OverloadedFuncDef, Decorator)) and "@" in fullname:
                yield_node = False
            if yield_node:
                yield fullname, symnode, info
            if isinstance(node, TypeInfo):
                yield from local_definitions(node.names, fullname, node, impl_only)

