
def mypyc_build(
    paths: list[str],
    compiler_options: CompilerOptions,
    *,
    separate: bool | list[tuple[list[str], str | None]] = False,
    only_compile_paths: Iterable[str] | None = None,
    skip_cgen_input: (
        tuple[list[list[tuple[str, str]]], list[tuple[str, list[str], bool]]] | None
    ) = None,
    always_use_shared_lib: bool = False,
) -> tuple[emitmodule.Groups, list[tuple[list[str], list[str]]], list[SourceDep]]:
    """Do the front and middle end of mypyc building, producing and writing out C source."""
    fscache = FileSystemCache()
    mypyc_sources, all_sources, options = get_mypy_config(
        paths, only_compile_paths, compiler_options, fscache
    )

    # We generate a shared lib if there are multiple modules or if any
    # of the modules are in package. (Because I didn't want to fuss
    # around with making the single module code handle packages.)
    use_shared_lib = (
        len(mypyc_sources) > 1
        or any("." in x.module for x in mypyc_sources)
        or any(is_package_source(x) for x in mypyc_sources)
        or always_use_shared_lib
    )

    groups = construct_groups(mypyc_sources, separate, use_shared_lib, compiler_options.group_name)

    if compiler_options.group_name is not None:
        assert len(groups) == 1, "If using custom group_name, only one group is expected"

    # We let the test harness just pass in the c file contents instead
    # so that it can do a corner-cutting version without full stubs.
    source_deps: list[SourceDep] = []
    if not skip_cgen_input:
        group_cfiles, ops_text, source_deps = generate_c(
            all_sources, options, groups, fscache, compiler_options=compiler_options
        )
        # TODO: unique names?
        write_file(os.path.join(compiler_options.target_dir, "ops.txt"), ops_text)
    else:
        group_cfiles = skip_cgen_input[0]
        source_deps = [
            SourceDep(path, include_dirs=dirs, internal=internal)
            for (path, dirs, internal) in skip_cgen_input[1]
        ]

    # Write out the generated C and collect the files for each group.
    # Should this be here??
    #
    # Header resolution is deferred to a second pass: a header in one group may include a header
    # generated by another group, so resolving here misses cross-group deps for groups processed first.
    pending: list[list[tuple[str, list[tuple[bool, str]]]]] = []
    for cfiles in group_cfiles:
        per_cfile_deps: list[tuple[str, list[tuple[bool, str]]]] = []
        for cfile, ctext in cfiles:
            cfile = os.path.join(compiler_options.target_dir, cfile)

            # Empty contents marks a file the previous run already wrote
            # (fully-cached group): skip the rewrite and just reuse it.
            if ctext and not options.mypyc_skip_c_generation:
                write_file(cfile, ctext)

            # For fully-cached groups ctext is empty; read the on-disk .c so the dep resolver
            # can walk its transitive header chain and populate Extension.depends. Otherwise,
            # cross-group export-table header changes (e.g. a new class shifting struct offsets)
            # won't trigger a recompile of this cached consumer's .o.
            if not ctext and os.path.exists(cfile):
                try:
                    with open(cfile, encoding="utf-8") as _f:
                        ctext = _f.read()
                except OSError:
                    pass
            per_cfile_deps.append((cfile, get_header_deps([(cfile, ctext)])))
        pending.append(per_cfile_deps)

    # Second pass: assemble each group's .c filenames and resolve transitive deps now that every group's
    # headers are on disk. See resolve_cfile_deps for the rules.
    group_cfilenames: list[tuple[list[str], list[str]]] = []
    for per_cfile in pending:
        cfilenames = [cf for cf, _ in per_cfile if os.path.splitext(cf)[1] == ".c"]
        deps_set: set[str] = set()
        for cfile_full, dep_names in per_cfile:
            deps_set.update(
                resolve_cfile_deps(
                    os.path.dirname(cfile_full), dep_names, compiler_options.target_dir
                )
            )
        group_cfilenames.append((cfilenames, sorted(deps_set)))

    return groups, group_cfilenames, source_deps

