
def render_to_text_as_root(
    root_node: rendering_parts.RenderableTreePart,
    roundtrip: bool = False,
    strip_trailing_whitespace: bool = True,
    strip_whitespace_lines: bool = True,
) -> str:
  """Renders a root node to text.

  Args:
    root_node: The root node to render.
    roundtrip: Whether to render in roundtrip mode.
    strip_trailing_whitespace: Whether to remove trailing whitespace from lines.
    strip_whitespace_lines: Whether to remove lines that are entirely
      whitespace. These lines can sometimes be generated by layout code being
      conservative about line breaks. Should only be True if
      `strip_trailing_whitespace` is True.

  Returns:
    Text for the rendered node.
  """
  if strip_whitespace_lines and not strip_trailing_whitespace:
    raise ValueError(
        "strip_whitespace_lines must be False if "
        "strip_trailing_whitespace is False."
    )

  render_context = {}
  if roundtrip:
    render_context[foldable_impl.ABBREVIATION_THRESHOLD_KEY] = (
        abbreviation.roundtrip_abbreviation_threshold.get()
    )
  else:
    render_context[foldable_impl.ABBREVIATION_THRESHOLD_KEY] = (
        abbreviation.abbreviation_threshold.get()
    )

  stream = io.StringIO()
  root_node.render_to_text(
      stream,
      expanded_parent=True,
      indent=0,
      roundtrip_mode=roundtrip,
      render_context=render_context,
  )
  result = stream.getvalue()

  if strip_trailing_whitespace:
    trimmed_lines = []
    for line in result.split("\n"):
      line = line.rstrip()
      if line or not strip_whitespace_lines:
        trimmed_lines.append(line)
    result = "\n".join(trimmed_lines)
  return result

