
def test_from_exp_coords(xp, dim: int):
    shape = (dim,) * (dim - 1)
    # example from 3.3 of
    # https://hades.mech.northwestern.edu/images/2/25/MR-v2.pdf
    dtype = xpx.default_dtype(xp)
    angle1 = np.deg2rad(30.0)
    mat = xp.asarray([
        [np.cos(angle1), -np.sin(angle1), 0.0, 1.0],
        [np.sin(angle1), np.cos(angle1), 0.0, 2.0],
        [0.0, 0.0, 1.0, 0.0],
        [0.0, 0.0, 0.0, 1.0]
    ], dtype=dtype)
    mat = xp.tile(mat, shape + (1, 1))
    tf1 = RigidTransform.from_matrix(mat)
    angle2 = np.deg2rad(60.0)
    mat = xp.asarray([
        [np.cos(angle2), -np.sin(angle2), 0.0, 2.0],
        [np.sin(angle2), np.cos(angle2), 0.0, 1.0],
        [0.0, 0.0, 1.0, 0.0],
        [0.0, 0.0, 0.0, 1.0]
    ], dtype=dtype)
    mat = xp.tile(mat, shape + (1, 1))
    tf2 = RigidTransform.from_matrix(mat)
    expected = tf2 * tf1.inv()
    deg2rag = xp.asarray(np.deg2rad(30.0))
    exp_coords = deg2rag * xp.asarray([0.0, 0.0, 1.0, 3.37, -3.37, 0.0])
    exp_coords = xp.tile(exp_coords, shape + (1,))
    actual = RigidTransform.from_exp_coords(exp_coords)
    xp_assert_close(actual.as_matrix(), expected.as_matrix(), atol=1e-2)

    # test cases generated by comparison to pytransform3d
    exp_coords = xp.asarray([
        [-2.01041204, -0.52983629, 0.65773501,
         0.10386614, 0.05855009, 0.54959179],
        [-0.22537438, -0.24132627, -2.4747121,
         -0.09158594,  1.88075832, -0.03197204]
    ])
    exp_coords = xp.tile(exp_coords, shape + (1,))
    expected_matrix = xp.asarray([
        [[0.76406621, 0.10504613, -0.63652819, -0.10209961],
         [0.59956454, -0.47987325, 0.64050295, 0.40158789],
         [-0.2381705, -0.87102639, -0.42963687, 0.19637636],
         [0., 0., 0., 1.]],
        [[-0.78446989, 0.61157488, 0.10287448, 1.33330055],
         [-0.58017785, -0.78232107, 0.22664378, 0.52660831],
         [0.21909052, 0.11810973, 0.96852952, -0.02968529],
         [0., 0., 0., 1.]]
    ])
    expected_matrix = xp.tile(expected_matrix, shape + (1, 1))
    xp_assert_close(
        RigidTransform.from_exp_coords(exp_coords).as_matrix(),
        expected_matrix, atol=1e-8)

    # identity
    expected_matrix = xp.tile(xp.eye(4), shape + (1, 1))
    exp_coords = xp.zeros(shape + (6,), dtype=dtype)
    xp_assert_close(
        RigidTransform.from_exp_coords(exp_coords).as_matrix(),
        expected_matrix, atol=1e-12)

    # only translation
    expected_matrix = xp.asarray([
        [[1.0, 0.0, 0.0, 3.0],
         [0.0, 1.0, 0.0, -5.4],
         [0.0, 0.0, 1.0, 100.2],
         [0.0, 0.0, 0.0, 1.0]],
        [[1.0, 0.0, 0.0, -3.0],
         [0.0, 1.0, 0.0, 13.3],
         [0.0, 0.0, 1.0, 1.3],
         [0.0, 0.0, 0.0, 1.0]]
    ])
    expected_matrix = xp.tile(expected_matrix, shape + (1, 1, 1))
    exp_coords = xp.asarray([
        [0.0, 0.0, 0.0, 3.0, -5.4, 100.2],
        [0.0, 0.0, 0.0, -3.0, 13.3, 1.3],
    ])
    exp_coords = xp.tile(exp_coords, shape + (1, 1))
    actual = RigidTransform.from_exp_coords(exp_coords)
    xp_assert_close(actual.as_matrix(), expected_matrix, atol=1e-12)

    # only rotation
    angles = xp.asarray([[34, -12, 0.5], [-102, -55, 30]])
    angles = xp.tile(angles, shape + (1, 1))
    rot = Rotation.from_euler('zyx', angles, degrees=True)
    rotvec = rot.as_rotvec()
    expected_matrix = xp.tile(xp.eye(4), shape + (2, 1, 1))
    expected_matrix = xpx.at(expected_matrix)[..., :3, :3].set(rot.as_matrix())
    exp_coords = xp.concat((rotvec, xp.zeros_like(rotvec)), axis=-1)
    actual = RigidTransform.from_exp_coords(exp_coords)
    xp_assert_close(actual.as_matrix(), expected_matrix, atol=1e-12)

