
def write_new_configs(config_path, new_weights):
    lines = ["# AUTOGENERATED BY ARCHITECTURE TEAM", "DEFAULT_ARCHETYPE_WEIGHTS = {"]
    for arch, weights in new_weights.items():
        lines.append(f'    "{arch}": {weights},')
    lines.append("}")
    lines.append("")
    Path(config_path).write_text("\n".join(lines), encoding="utf-8")
    logger.info(f"Updated {config_path} successfully.")

