import logging
import json
from pathlib import Path
from factory.configs import DEFAULT_ARCHETYPE_WEIGHTS

logger = logging.getLogger("ArchitectureTeam")

class ArchitectureTeam:
    def __init__(self, config_path: str = "factory/configs.py"):
        self.config_path = Path(config_path)

    def execute_adjustments(self, meta_summary: dict):
        """
        Autonomously adjusts architectural hyperparameters based on Kaggle meta shifts.
        Applies hardcoded safety limits to prevent the AI from breaking the codebase.
        """
        logger.info("Architecture Team evaluating meta-learning summary for adjustments...")
        if not meta_summary:
            logger.info("No meta-learning summary provided. Skipping adjustments.")
            return

        # Simple autonomous logic: if we are losing a lot, slightly perturb the weights
        # to adapt, based on the meta summary (e.g., increasing recovery weight if losing fast).
        # We will bound the adjustments to ensure stability.

        try:
            current_weights = dict(DEFAULT_ARCHETYPE_WEIGHTS)
            adjusted = False

            # Example logic: if the opponent win rate is high, shift weights towards consistency
            anti_patterns = meta_summary.get("anti_patterns", [])
            for pattern in anti_patterns:
                if "brick" in str(pattern).lower() or "timeout" in str(pattern).lower():
                    logger.info("Architecture Team detected 'brick/timeout' meta. Bumping consistency weights.")
                    for arch in current_weights:
                        w = list(current_weights[arch])
                        # Bump consistency (index 0), lower others slightly
                        w[0] = min(0.8, w[0] + 0.05)
                        w[1] = max(0.05, w[1] - 0.02)
                        w[2] = max(0.05, w[2] - 0.02)
                        w[3] = max(0.05, w[3] - 0.01)
                        
                        # Normalize to sum to 1.0
                        total = sum(w)
                        current_weights[arch] = tuple(round(x / total, 3) for x in w)
                        adjusted = True

            if adjusted:
                logger.info("Writing adjusted configurations to disk.")
                self._write_new_configs(current_weights)
            else:
                logger.info("No actionable architecture shifts required.")

        except Exception as e:
            logger.error(f"Architecture Team failed to adjust configs: {e}")

    def _write_new_configs(self, new_weights: dict):
        """Rewrites the configs.py file with the new weights, keeping under limits."""
        lines = ["# AUTOGENERATED BY ARCHITECTURE TEAM", "DEFAULT_ARCHETYPE_WEIGHTS = {"]
        for arch, weights in new_weights.items():
            lines.append(f'    "{arch}": {weights},')
        lines.append("}")
        lines.append("")
        
        self.config_path.write_text("\n".join(lines), encoding="utf-8")
        logger.info(f"Updated {self.config_path} successfully.")
